spring:
  application:
    name: spring-cloud-demo-web-admin-ribbon
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/