spring:
  application:
    name: spring-cloud-demo-admin
  zipkin:
    base-url: http:localhost:9411
server:
  port: 8084
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info