version: '3'
services:
  spring-cloud-web-admin-ribbon:
    restart: always
    image: spring-cloud-web-admin-ribbon:v1
    container_name: spring-cloud-web-admin-ribbon
    ports:
      - 8764:8764
    environment:
      TZ: Asia/Shanghai

