spring:
  application:
    name: spring-cloud-demo-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/shadaileng/spring-cloud-demo.git
          search-paths: config
  zipkin:
    base-url: http://192.168.96.1:9411
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://192.168.96.1:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info