spring:
  application:
    name: spring-cloud-demo-admin
  zipkin:
    base-url: http://10.254.198.150:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.254.198.150:8761/eureka/
