spring:
  application:
    name: spring-cloud-demo-service-admin
  zipkin:
    base-url: http://192.168.96.1:9411
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.96.1:8761/eureka/
