spring:
  datasource:
    druid:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite::resource:data/demo.db
      username:
      password:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

mybatis:
  configuration:
    use-generated-keys: true
    cache-enabled: false
