spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: true
host:
  sso: http://${ipaddr}:8900
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断器超时时间, 默认: 1000毫秒
            timeoutInMilliseconds: 30000