ipaddr: 116.85.54.176
spring:
  application:
    name: spring-cloud-demo-eureka
  zipkin:
    base-url: http://${ipaddr}:9411
server:
  port: 8761

eureka:
  instance:
    hostname: ${ipaddr}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
