spring:
  application:
    name: spring-cloud-demo-eureka
  zipkin:
    base-url: http://10.254.198.150:9411
server:
  port: 8761

eureka:
  instance:
    hostname: 10.254.198.150
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
