spring:
  application:
    name: spring-cloud-demo-eureka
  zipkin:
    base-url: http://192.168.96.1:9411
server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.96.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/