ipaddr: 116.85.54.176
ipreg: localhost
spring:
  application:
    name: spring-cloud-demo-eureka
server:
  port: 8761

eureka:
  instance:
    hostname: ${ipaddr}
  client:
    register-with-eureka: false
    fetch-registry: false
