ipaddr: 116.85.54.176
ipreg: ${ipaddr}
server:
  port: 6640
spring:
  application:
    name: spring-cloud-demo-gateway
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
            - dummy
      routes:
        - id: web-admin
          # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://spring-cloud-demo-web-admin-feign
          predicates:
            # 重点！转发该路径！,/admin/**,
            - Path=/admin/**
          # http://localhost:6601/admin/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上 admin
          # 而不是我们期望的去掉 admin, 只保留**部分
          filters:
            - StripPrefix=1
        - id: sso
          uri: lb://spring-cloud-demo-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1