ipaddr: localhost
ipreg: localhost
server:
  port: 8800
spring:
  application:
    name: spring-cloud-demo-service-redis
  redis:
    host: ${ipaddr}
    #  数据库索引
    database: 0
    # 远程服务器端口
    port: 6379
    # 链接超时时间(毫秒)
    timeout: 200
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0