ipaddr: 116.85.54.176
ipreg: 116.85.54.176
server:
  port: 8800
spring:
  application:
    name: spring-cloud-demo-service-redis
  redis:
    host: ${ipaddr}
    #  数据库索引
    database: 0
    # 远程服务器端口
    port: 6379
    # 链接超时时间(毫秒)
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)默认 8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
