spring:
  application:
    name: spring-cloud-demo-service-admin
  zipkin:
    base-url: http://10.254.198.150:9411

server:
  port: 8861

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.254.198.150:8761/eureka/
