ipaddr: 10.254.198.150
spring:
  application:
    name: spring-cloud-demo-service-admin
  zipkin:
    base-url: http://${ipaddr}:9411
  datasource:
    druid:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:resource:data/demo.db
      username:
      password:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

server:
  port: 8861

eureka:
  instance:
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 注册的实例名
    instance-id: ${ipaddr}:${server.port}
    # 指定此实例的ip
    ip-address: ${ipaddr}
  client:
    serviceUrl:
      defaultZone: http://${ipaddr}:8761/eureka/
