spring:
  application:
    name: spring-cloud-demo-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8861

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/