ipaddr: 116.85.54.176
ipreg: ${ipaddr}
server:
  port: 8900
spring:
  application:
    name: spring-cloud-demo-sso
  #不覆盖本地配置文件
  cloud:
    config:
      override-none: true
      override-system-properties: false