server:
  port: 8900
spring:
  application:
    name: spring-cloud-demo-sso
#  thymeleaf:
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html
#  zipkin:
#    base-url: http://localhost:9411

#feign:
#  hystrix:
#    enabled: true

#eureka:
#  instance:
#    # 注册时使用ip而不是主机名
#    prefer-ip-address: true
#    # 注册的实例名
#    instance-id: localhost:${server.port}
#    # 指定此实例的ip
#    ip-address: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
