spring:
  application:
    name: spring-cloud-demo-web-admin-feign
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
