spring:
  application:
    name: spring-cloud-demo-web-admin-feign
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  cloud:
    config:
      uri: http://localhost:8888
      label: master
      name: web-admin-feign
      profile: dev

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
