ipaddr: 10.254.198.150
spring:
  application:
    name: spring-cloud-demo-web-admin-ribbon
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://${ipaddr}:9411
server:
  port: 8764

eureka:
  instance:
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 注册的实例名
    instance-id: ${ipaddr}:${server.port}
    # 指定此实例的ip
    ip-address: ${ipaddr}
  client:
    serviceUrl:
      defaultZone: http://${ipaddr}:8761/eureka/
