ipaddr: 116.85.54.176
ipreg: localhost
server:
  port: 8961
spring:
  application:
    name: spring-cloud-demo-web-admin-feign
#  zipkin:
#    base-url: http://${ipaddr}:9411
#  thymeleaf:
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html

#feign:
#  hystrix:
#    enabled: true

#eureka:
#  instance:
#    # 注册时使用ip而不是主机名
#    prefer-ip-address: true
#    # 注册的实例名
#    instance-id: ${ipreg}:${server.port}
#    # 指定此实例的ip
#    ip-address: ${ipreg}
#  client:
#    serviceUrl:
#      defaultZone: http://${ipaddr}:8761/eureka/
