ipaddr: 10.254.198.150
spring:
  application:
    name: spring-cloud-demo-zipkin
server:
  port: 9411
eureka:
  instance:
    # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 注册的实例名
    instance-id: ${ipaddr}:${server.port}
    # 指定此实例的ip
    ip-address: ${ipaddr}
  client:
    service-url:
      defaultZone: http://${ipaddr}:8761/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false
