spring:
  application:
    name: spring-cloud-demo-zipkin
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://10.254.198.150:8761/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false
