ipaddr: 116.85.54.176
ipreg: localhost
spring:
  application:
    name: spring-cloud-demo-zuul
server:
  port: 8769
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-demo-web-admin-feign
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-demo-web-admin-ribbon
